spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NagamSiva/config-repository
          clone-on-start: true
#management:
#  security:
#    enabled: false