server:
  port: 9898
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test123
    url: jdbc:mysql://localhost:3306/securityRagu
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: SECURITY-SERVICE
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/